require('plugins')
require('keybindings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('saga-config')
require('dap-config')
require('cmp-config')
require('telescope-dap-config')
require('dap-ui-config')
--vim.cmd('colorscheme nord')
--require('dap-config')
vim.cmd[[colorscheme ayu-dark]]

